title: "Performance Labs"
description: "Rendimiento deportivo con ciencia, datos y criterio."
url: "https://mitsuotanida.github.io"
baseurl: "/performanceblog"
timezone: America/Santiago
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
author: "Performance Labs"
collections_dir: .
